---
default_stages:
  - commit
repos:
  - hooks:
      - args:
          - --py37-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
  - hooks:
      - id: black
        language_version: python3.7
    repo: https://github.com/psf/black
    rev: 22.10.0
  - hooks:
      - additional_dependencies:
          - black==22.8.0
        id: blacken-docs
    repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
  - hooks:
      - id: isort
    repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
  - hooks:
      - args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --exclude
          - __init__.py
        id: autoflake
    repo: https://github.com/myint/autoflake
    rev: v1.7.7
  - hooks:
      - id: trailing-whitespace
        stages:
          - commit
        exclude: ".bumpversion.cfg"
      - id: end-of-file-fixer
        stages:
          - commit
      - id: check-yaml
      - id: check-case-conflict
      - id: check-json
      - args:
          - --remove
        id: fix-encoding-pragma
      - args:
          - --fix=lf
        id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: name-tests-test
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-executables-have-shebangs
        stages:
          - commit
      - id: debug-statements
      - id: check-xml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: python-no-log-warn
      - id: python-no-eval
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
  - hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests==2.28.11]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml, --strict]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: [beautifulsoup4==4.11.1, requests==2.28.1]
        exclude: "revivelink_bypass/tests/.*"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
